// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-nneZUKNsqg41q-ChTgi27ssoc2PSZlI',
    appId: '1:57021832373:web:95ab337c54dfa9ed9872fc',
    messagingSenderId: '57021832373',
    projectId: 'fir-login-e43fc',
    authDomain: 'fir-login-e43fc.firebaseapp.com',
    storageBucket: 'fir-login-e43fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2b2hKPcUrEEOd4elvwRElRNprIiEtQVM',
    appId: '1:57021832373:android:095ef49656d6cac69872fc',
    messagingSenderId: '57021832373',
    projectId: 'fir-login-e43fc',
    storageBucket: 'fir-login-e43fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu8D9t7cC_LZLIXa2b_-an1PT9jcu_Tsc',
    appId: '1:57021832373:ios:ee36cdccc12ed5d99872fc',
    messagingSenderId: '57021832373',
    projectId: 'fir-login-e43fc',
    storageBucket: 'fir-login-e43fc.appspot.com',
    iosClientId: '57021832373-4pfbrco2imfielu4nrusvqqffe579s3c.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLogin',
  );
}
